### PR TITLE
Add IEEE camera generation

### PR DESCRIPTION
**Pull request by chelini**

### CODE REVIEW

**Comment by tobiasgrosser** [comment]
I just went over my github mails and saw some activities here. @math-fehr, is there a plan to upstream this branch?

**Comment by math-fehr** [comment]
It's not mergeable yet, i need to fix some bugs first.
I'll work on it this/next week!

**Comment by tobiasgrosser** [comment]
Cool.

**Comment by math-fehr** [comment]
This should work now!
Tell me if there is anything that should change before I merge it!

**Comment by anurudhp** [comment]
Bump, can we merge this?

**Pull request merged**
